create table "public"."clicks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "link" bigint not null
);


alter table "public"."clicks" enable row level security;

CREATE UNIQUE INDEX clicks_pkey ON public.clicks USING btree (id);

alter table "public"."clicks" add constraint "clicks_pkey" PRIMARY KEY using index "clicks_pkey";

alter table "public"."clicks" add constraint "clicks_link_fkey" FOREIGN KEY (link) REFERENCES links(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."clicks" validate constraint "clicks_link_fkey";

grant delete on table "public"."clicks" to "anon";

grant insert on table "public"."clicks" to "anon";

grant references on table "public"."clicks" to "anon";

grant select on table "public"."clicks" to "anon";

grant trigger on table "public"."clicks" to "anon";

grant truncate on table "public"."clicks" to "anon";

grant update on table "public"."clicks" to "anon";

grant delete on table "public"."clicks" to "authenticated";

grant insert on table "public"."clicks" to "authenticated";

grant references on table "public"."clicks" to "authenticated";

grant select on table "public"."clicks" to "authenticated";

grant trigger on table "public"."clicks" to "authenticated";

grant truncate on table "public"."clicks" to "authenticated";

grant update on table "public"."clicks" to "authenticated";

grant delete on table "public"."clicks" to "service_role";

grant insert on table "public"."clicks" to "service_role";

grant references on table "public"."clicks" to "service_role";

grant select on table "public"."clicks" to "service_role";

grant trigger on table "public"."clicks" to "service_role";

grant truncate on table "public"."clicks" to "service_role";

grant update on table "public"."clicks" to "service_role";


